apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgAyU+DcWltG0IO0w7ka4KeJRl8STJl2u8egrYxQtMCA7Tq6orPTA4kMTSlaasnQW28ldbGZnkHAD5DoBFgo+Ky+0XXXb5q+Z7DMKXIXyhTj2eUo7AB3UGlpHAwvbtqMmFusPhN7ogA+ZUkU16c19DloG1uVVFPMZ4OQDfMedpscviPe+KUafajFFRqqTx4Cas7+wzp4GCnO2rcALA8X3x6zLUeyhznH66eEqwLAJD9z1h+kq2rzN0jrpFiaLo5T9RYFEW8cO5Y+yL4ncMlZ/Rx3gwX6CL0dWgs3QsZQkj2hOg6DPr0Pk/rusrwZTWNIIEjTvYLT49fWclzzxVxcaHGkLHPjS3r5rbYRKy22xLqUNuqnYKH733I2ZXYCFIV64o5mZo/QhSfNUZmKkICsauEf0i+u8MMO0gZAzWJj/qKHJsSCxlBuR84YKdTYQcoU33ARe47IRe9ekKnncDcr8dQtWGNOgSAa1QAr9phmkn7bzWMxZb57gROduX0MdTT4xlnDULV85cu9fMBuyNMbVNphs74I13oWyNNEwXOsaHvqCeRY6MQ+O/HSIIIMkJxSK2l6bWMr9+GIXRRwlRATvg4TYCuNFTgKwUgV4zSj6EkCV+k+71alzrIqXKbPbJR313YYZ+Ox4B6ElSDINY8OG+GeBEraKNGQyQodMKF2k3/gEzkrLrmr+YuGT2zoZtldzMYOKZQWN6pFZoDOkNPXgcQlGCu/KYBUGeLlvRaNAy/3ecRYEWBnoTxBtffrOdjDzrlg2zl6kplqvWwx3aMp5lluFihfRVfoexY5VVm58nJp7d55fNz3vQI0arZ+ztq79OdmW2tCqTL0FfWpA5/kt0ioBBw3yPHrXqNGXuoT+RL6wpTFlKs9w/r3//ZgBO/9ligyKEx3vgpp/daw6QHQSDMHH6gMFCaVBV0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

