apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgB1+xdzlLBf4zOvDPglg9hqHaV4UOfQ+HdY82RJTnK2xjHB9X4orhqKkyQSVKFNeoafrPs/cWEV3ADm7CYXBIdwDiacnA7Na8JoCfhUDBQm/3YGe/iRBUH4nHV0ztpEuNJMwRWY/TUy/hd9F8Ztp3tgGIEcEOVxiWUYLabwwAuWU/c0X9Txm5qZsxsy3O6MpY9oWsXLPsHY+A7hMKvOO7mKK1EMB1EpeI0NSA/q0hGK6aCojGJi7ov00XbqM7d8g3sfLMOR56jWlsjqOtM9T9r+xT54BLfZYO5WU3wO3vZAQ16fHhozGcTr1ouQ8ajuIegfjPovbtnySiKBIsemjZA27kUwnLasYiigltC9R75+fviw+WzZqRZpEn/U8BI3sNF8bA024iG1Ya1RiBZ65xBCnQJhDjQUiy1Tm3vQ13ZT4myPVbqqyxYJiC10b88Vu4pyp9E3/wNITQeV0zbw+j1Xvg/tl+BVc1oj6gX/OanAUQ9Sr4v6keuL5tiMZ82InpomrP/4VijGGNsg6S9RFKH0MuYdQEGIAgEaGRP4ApDQUznLGuE++FbkgIzDTSdXcGNWnGvoe+zRYaidIVXgfszoRVVOfgOgd9N/H/cK4y9od5Kr71Izfm/dE0b0pMZIGpfLqtYJi/0Wzv3EEK41vfBqPq02FwsIMDRlEOe+Q4NeJNpVLDAqRw5NbMwVaQqzFUYbVT3hz7S57gEbTyVcMW4ZezNV1Agakm/zVPIuwVVsloj5K9bMXow27GtxowRxm1b2zNe85Ul29KDC+Y5OsUEGR8m09NuUTaxYHA4p/x+WARgtYfMCOOMpb0baDgUgI0Nbs8BU5z8S7sd7p/y11rt0KOedeItPHse/E+pIPtzxZLq1Jmuwu+Rg5z2LpZJW1EsDIjxHcVaINISeMPowsocphVQiU5lGb24J+NC3F62WbeTBM7Vvk2qGtVcbn0dBDdNqplL+XO2lcBTWwWa+B6VZ/7IxKYY5UiyecW6EhxvoVOr+eMQlXg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

