apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgA19ymoiR7U3hyRkw+l2o4zjWkg0mwj5kMYWhJ1+uecBE7PdmvZ5Nf85uHWoYzbl9VghZ4A4lWtJMHRjKuKs5TVNoqhKCLmVa6xVyb7rAD3nwsq4FV71GTGqAFvqHuYK83O9sv5LqKGtb9154de6LB7Ph4wxB7Cyquhi/LAqXVie75fGBxF+nf1LSJeCbAmHelV2ExJgQZcqKLFHKyqdGFPiEi9ITtaMziLNWjYKCb4bb/EAZDwnXcyJnrat5IuLkhEYALHlJCdaYNeYPtJjAa3jHc0vwicC6LpdQMZvrddFnhe7NoTjKNi+vUP7LZnPuwC36EFBgW1qMo2VfXbPRVEgqYOelvPVP3Jre4r13RsAZnGJxQsyfUy4Dqy/bRRK9PHSDjmIzCy6xLOwP6y0bAMobXJBTR5y0OX+c/QE3pgvXLkHhk3bQFHpBQZDCOYGmJmbX+WXPL6aIHrUX9Cue/RFRdHZMmKauQPyFrkkckYC8IsaBjvHZADfwMks/2nxwF+MdKCZHxm+OeyVMtDj948W2xVFN4sqEoKPHwGKAH2p21ts+LVxKCrsJLHtGx5/VNoU6LLLtmqf6O/rbAic7FulWoq/w9bCSuxUbM2oV/ADKTyTh2/k8CsvUjQwQ0HkxCbGj6O4Bg76jd+LYG1WQFnnQy92nIG4uoyt4tb+z/sgXR9Brnbzkz1A05y89xcxTct/9+LGzd6/yWgLKoqY7CWB7dSimQ7Bt/ujQhQ6L6qCDXom/DV0oqa
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

