apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAhD2Yr/Fe8qX76++WfyrhhtRu5OU081jsxoS9oq0GeaNlTWpouhTOpNaeh1DVtYOmOZWac2rPLOSNw7BcgHEQhXJiQGrHS2iDUWyXL6NS5xQYF/MgA1r7IekOS/f4nU4qXTbKXfst98u6iS5Oehgrm9o5sweWLBtJ1gRDUTTW+/fdPc0tvjsadZJNB1HYyi8+6TfQ23ZT/RlTIMblQcKWPVtSr1RHj/vrv2NL0GW19Zjo2fCLPZJILai7VDPAWy7F5EFI4OVqgXqHwDgPVJoxQlQNuwpgsYOh9WcvFnnxbULXpjzWsAduUZZDwksOAI1VtYN8sOSdb+s52u9CmwSbSkA5KHBHoix7OUv2gUuWmN+rOfbKbOyGYIiaWV3kh+sCU5fuQmuCnibGL4GaLfy9ch7VUx6ibEKKY6YMx/x4o6e2EDeO0EEJV/qmO2ZiVVMciqKvnlGo3N1BX2Tz4czi5atILOsnY1qW0d3dGmcaq1Rr8M0ySwUsf5C9CW+3PasP6KVL4Rp8Js8/xqjcDXlj/zRgIjF3Bcg4tgYWKBFjISoMV6Gz8GH1WamLWG0CQCpZxbseszWGmGKgumj0SnMIIhE9xzy5VcjBcj8tIvf15SZAECQn4swPi/Bndgn7KEuobddiDTurR8uAn4XdVyc+ks1R4GyUtVGNhW+WtCoQ3ehfmMfXNZDvfXiud8YVjVI6U02WsXtTldpn57V+7SC/ErYuarfYzyddtlTqUI+KuG58QmXk+IGhB
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

