apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCWxEQFa3cMY88eCnROvnN+25VuZqZSf5jUsRXsOhUVGT8RCLkRYvCVB62i5Zg4biRYRHayRcqufzhHaWBX6ek1w5ejehy0fFxwd89yCd4h1Mmt4Tre7Gg39pIp9WkvYxZpmjBxmmbcSylXkWUFuWDegIv6JTp2+nhlSmhhgH9ai28XdEvHp5laiMnJSbC9ubb7bmBxYVy+rH5G3yrx/TUJMHVadtbBm9iWtgTDY3W9vRwzqjg2UeS3rfqmn5NyEWuaNE0RufQc86tMNe+OLn33S6SrBeRjDqlyWr+2m0Uo8tmjuqLu5GOTs3RsxK0gIOJxLh8Y6sp3Zo/DPDusNdPZn33yPx0RfV5BZpM07j/1Zul1VARFoL6QEpzz4evXnrfbXiXJmVwFUI028oPZVBw9ySq7g2GHEcv17RPDzb7CVfKcccFZYkxl/z3PIdpcqEQgb3jq+Bzu0nszM+v+KYhYdRuYPLlhygBEteDml6AkqUHnY+gb/yw4hGdXaEZbV2UIRrQJl+oejkMJX4s2gctcbgGq5qkAqpzNHDUFthz5xadV6Z3DDj0eX790qTGd31gF95h4W2oK78Yorl1cunqnqgg8ES9xlxSGBxSJAa7FKGvDvL5QCXW0/nfOvLz1c/1QHOBc7wmIYRwtQVJ8hi0FfrvPsHeBsxCXuA/sh/PUhS+PejZraLaUPBILPxsKwLJvIgwhESCYO9aVbHgKBNWwZgXoztlNAASY96KrPVCL1mfL35qgWHBZ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

