apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCEHIeriZ2CrqXMe4MoEfqcSe+0+z4KPvg5o8uAgLuRfZ9/B+xnvCIVO3AJAqv3ul79QCSeRG8YyBg4/LNoMU6zC9zwdZepw6yEOWFS9JE0x0v8LA5PyRHteVXZ4RP0xleVq0LVXkO+Aijc9qYLZYiVf1OhpIB2gyKlyH/HSWyikc/TNFsC2Ds75TlzSXqoHXh+3PF7enhkz6pX/9MVXOP62ExLwSNAQFzeiq4RayqQKFvdMy89M7m36QdSVbg0x4PFhtg3Ez4gq238Ea7FGrBiu7dd/Z+5tHMzlqW62OrWIxKjCkgnZXTS2KRz2LTus8BoAUZL1T8IdUs+bNFm0pp+KPO6spv7xnkoOvlZGfwnhpOjosI5YUD+0+rnhImPKI5x6pkn2O8xgZqtDpwRkFFX8SgCYiRi75+FpFEVuMflO/cUU5Y7n6rDA6o0M/me0y+QvF4UrKIzxnLOw0sGrGRjauy57YWhdAuXH7Y8XMeSp91JoMg/PeRbx0ISSSt+d53Sk4PCk4Imkn78Txk2+0SwcgWtZtvgiwvtj44M/Kyma6AoijKYCcu0KdSfTLTBJ3VZkE5exg1cHfoKyjT96xG5qfur80evt0GeMOuOX1zcIudPQIwXUbyauPWzhvwkkq1x3XUtKLgT3aV6cpLcTOvDPPzPFr98U4X6cd0DAhjW6G22PRIdvdNss5mFMEKViZgcQCGCR7HhiHU3DhLfydFB/usy+iOcksIp7rcINwzQfZBKa/KAHdqv
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

